<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <OutputType>Exe</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.mtp" Version="10.0.1" />
        <PackageReference Include="xunit.v3" Version="4.0.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\TestUtilities\Lithan.Core.TestUtilities.XUnit\Lithan.Core.TestUtilities.XUnit.csproj" />
        <ProjectReference Include="..\Lithan.Core.Application\Lithan.Core.Application.csproj" />
    </ItemGroup>

</Project>
